name: CD Build

on:
  push:
    branches: [ main ]

jobs:
  run-cd-build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v4
      - name: Setup Node.js
        uses: actions/setup-node@v3.8.1
        with:
          node-version: 18
      - name: Make build for deployment
        run: |
          npm install -D
          npm run build
        # Add steps if required
