name: Start new repo

on:
  push:
    branches: [ main ]

permissions:
  contents: write

jobs:
  run-initialization:
    if: ${{ !github.event.repository.is_template }}
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v4
      - name: Init with new contents
        env:
            THIS_FILE: ".github/workflows/init.yml"
            SETUP_DIR: ".github/variable"
            NEW_BRANCH: "feat/v1"
            OWNER: ${{ github.event.repository.owner.name }}
            REPO: ${{ github.event.repository.name }}
        run: |
            for file in $SETUP_DIR/*; do
            sed -i 's/$OWNER/'"$OWNER"'/g' $file
            sed -i 's/$REPO/'"$REPO"'/g' $file
            sed -i 's/$NAME/'"${REPO,,}"'/g' $file
            mv $file ./$(basename $file)
            done
            rm -rf $SETUP_DIR $THIS_FILE
            git config --global user.email "41898282+github-actions[bot]@users.noreply.github.com"
            git config --global user.name "github-actions[bot]"
            git add .
            git commit --amend --no-edit
            git push -f origin main
            git checkout -b $NEW_BRANCH
            git push origin $NEW_BRANCH
